### PR TITLE
#165957324 create /auth/signup endpoint

### PR DESCRIPTION
**Pull request by Eazybee**
#### What does this PR do?
-  create /auth/signup endpoint

#### Description of Task to be completed?
- create /auth/signup route
- check if user email exist
- encrypt the password before saving
- respond with a JSON obj
- respond with  jwt token
- validate inputs

#### How should this be manually tested?
- Clone this branch
- Run ```npm run start-dev```
- Send a post request to ```http://127.0.0.1:3000/api/v1/auth/signup```

#### Any background context you want to provide?
- You need node and npm installed
- Run ```npm install``` to install all dependencies 
- You need Postgres database
- Run ```cd src/db && sequelize db:migrate```
- Post data model ```
{
	"firstName": string,
	"lastName": string",
	"email": {string, email} ,
	"password": string
}```

#### What are the relevant pivotal tracker stories?
- #165957324 (https://www.pivotaltracker.com/story/show/165957324)

### CODE REVIEW

**Comment by Eazybee** [comment]
@akinyeleolat @frankly034 @EmmanuelSage @mosinmiloluwa01 
Please take a min to review this pull request and give feedback or consent to merge.

**Comment by EmmanuelSage** [comment]
Nice one Eazybee,
Would you check your .env file in git ignore, your password is online.
Would you also change the password in the config file to postgres?

Good job bro.

**Review by EmmanuelSage — COMMENTED** [review]
Nice one Eazybee,
Would you check your .env file in git ignore, your password is online.
Would you also change the password in the config file to postgres?

Good job bro.

**Comment by frankly034** [comment]
Nice job @Eazybee. 

Quick witted implementation of password hash using the User.beforeCreate(). 

Everything looks cool. 

Would it be better to move the dotenv.config() function outside the getToken() into the global file scope?

NIce job!

**Comment by Eazybee** [comment]
@EmmanuelSage  @frankly034 Thanks for your review. I have updated the code. you can review again.

**Comment by Sojisoyoye** [comment]
@Eazybee, Great job, It's cool.

**Pull request merged**
